# Generated by Django 3.1.5 on 2021-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='ID пользователя')),
                ('binance_api_key', models.CharField(blank=True, max_length=128, null=True, verbose_name='API ключ Binance')),
            ],
        ),
    ]
